"""Oracle tests for `geo-cedimento-elastico-newmark`, `legacy_compat=True` (`docs/BUILD_CONTRACT.md`
"Tests" §2). Fixtures generated by `tests/fixtures/gen_geo_cedimento_elastico_newmark_centro.py`
(sheet `Elastico_centrale_Newmark`) and `..._punto.py` (sheet `500`, plus the free golden cases
`400`/`350` -- `docs/architecture-batch2.md` §6)."""
import json
from pathlib import Path

import pytest

from strutture.geotechnics.cedimenti_elastico.models_newmark import NewmarkInput
from strutture.geotechnics.cedimenti_elastico.tool_newmark import run_newmark
from strutture.shared.units import kgcm2_to_mpa

FIXTURES = Path(__file__).parents[2] / "fixtures"
CENTRO_FIXTURE = json.loads((FIXTURES / "geo_cedimento_elastico_newmark_centro_oracle.json").read_text(encoding="utf-8"))
PUNTO_FIXTURE = json.loads((FIXTURES / "geo_cedimento_elastico_newmark_punto_oracle.json").read_text(encoding="utf-8"))

# Ground-surface stratigraphy of `Elastico_centrale_Newmark`'s D7:F11 (only overridden by case 3's
# "F7"), and of sheets `500`/`400`/`350`'s D15:F19 (each sheet's own defaults; only overridden by
# case 3's "F16" on `500`).
CENTRO_DEFAULT_STRATI = [
    {"z_top_m": 0.80, "z_bot_m": 4.80, "modulo_MPa": kgcm2_to_mpa(5500 / 98.0665)},
    {"z_top_m": 4.80, "z_bot_m": 5.80, "modulo_MPa": kgcm2_to_mpa(7000 / 98.0665)},
    {"z_top_m": 5.80, "z_bot_m": 6.60, "modulo_MPa": kgcm2_to_mpa(9000 / 98.0665)},
    {"z_top_m": 6.60, "z_bot_m": 32.60, "modulo_MPa": kgcm2_to_mpa(7000 / 98.0665)},
    {"z_top_m": 32.60, "z_bot_m": 120.0, "modulo_MPa": kgcm2_to_mpa(7000 / 98.0665)},
]
PUNTO_500_DEFAULT_STRATI = [
    {"z_top_m": 0.0, "z_bot_m": 15.0, "modulo_MPa": kgcm2_to_mpa(100)},
    {"z_top_m": 15.0, "z_bot_m": 16.0, "modulo_MPa": kgcm2_to_mpa(180)},
    {"z_top_m": 16.0, "z_bot_m": 17.0, "modulo_MPa": kgcm2_to_mpa(180)},
    {"z_top_m": 17.0, "z_bot_m": 30.0, "modulo_MPa": kgcm2_to_mpa(180)},
    {"z_top_m": 30.0, "z_bot_m": 120.0, "modulo_MPa": kgcm2_to_mpa(180)},
]
PUNTO_400_STRATI = [
    {"z_top_m": 0.0, "z_bot_m": 2.40, "modulo_MPa": kgcm2_to_mpa(80)},
    {"z_top_m": 2.40, "z_bot_m": 12.0, "modulo_MPa": kgcm2_to_mpa(200)},
    {"z_top_m": 12.0, "z_bot_m": 15.0, "modulo_MPa": kgcm2_to_mpa(120)},
    {"z_top_m": 15.0, "z_bot_m": 20.0, "modulo_MPa": kgcm2_to_mpa(120)},
    {"z_top_m": 20.0, "z_bot_m": 120.0, "modulo_MPa": kgcm2_to_mpa(120)},
]
PUNTO_350_STRATI = PUNTO_400_STRATI  # sheet `350` reuses the exact same D15:F19 stratigraphy


@pytest.mark.oracle
@pytest.mark.parametrize("case", CENTRO_FIXTURE, ids=range(len(CENTRO_FIXTURE)))
def test_oracle_centro(case: dict):
    overrides, outputs = case["inputs"], case["outputs"]
    strati = CENTRO_DEFAULT_STRATI
    if "F7" in overrides:
        strati = [{**strati[0], "modulo_MPa": kgcm2_to_mpa(overrides["F7"])}, *strati[1:]]
    inputs = NewmarkInput(
        modalita="CENTRO", q=overrides.get("D3", 0.5) * 98.0665, d=overrides.get("G1", 110) / 100,
        b=overrides.get("D1", 350) / 100, l=overrides.get("D2", 500) / 100, strati=strati, legacy_compat=True,
    )
    report = run_newmark(inputs)
    assert report.ok, report.errors
    assert report.data.centro.w_centro_cm == pytest.approx(outputs["U6"], rel=1e-6)
    assert report.data.centro.w_qa_cm == pytest.approx(outputs["Z6"], rel=1e-6)


def _punto_inputs(overrides: dict, strati: list[dict]) -> NewmarkInput:
    if "F16" in overrides:
        strati = [strati[0], {**strati[1], "modulo_MPa": kgcm2_to_mpa(overrides["F16"])}, *strati[2:]]
    side_p = overrides.get("F5", 4000) / 100
    side_q = overrides.get("F6", 4000) / 100
    e1 = overrides.get("F7", 2000) / 100
    e2 = overrides.get("F8", 2000) / 100
    return NewmarkInput(
        modalita="PUNTO", q=overrides.get("C1", 0.8) * 98.0665, d=overrides.get("G1", 220) / 100,
        side_p=side_p, side_q=side_q, e1=e1, e2=e2, strati=strati, legacy_compat=True,
    )


@pytest.mark.oracle
@pytest.mark.parametrize("case", PUNTO_FIXTURE[:4], ids=range(4))
def test_oracle_punto_500(case: dict):
    overrides, outputs = case["inputs"], case["outputs"]
    report = run_newmark(_punto_inputs(overrides, PUNTO_500_DEFAULT_STRATI))
    assert report.ok, report.errors
    assert report.data.punto.w_o_cm == pytest.approx(outputs["500!C2"], rel=1e-6)
    assert report.data.punto.w_o_prime_cm == pytest.approx(outputs["500!C3"], abs=1e-4)


@pytest.mark.oracle
def test_free_golden_case_400():
    outputs = PUNTO_FIXTURE[4]["outputs"]
    inputs = NewmarkInput(modalita="PUNTO", q=0.98 * 98.0665, d=2.20, side_p=4.0, side_q=4.0, e1=2.0, e2=2.0, strati=PUNTO_400_STRATI, legacy_compat=True)
    report = run_newmark(inputs)
    assert report.ok, report.errors
    assert report.data.punto.w_o_cm == pytest.approx(outputs["400!C2"], rel=1e-6)
    assert report.data.punto.w_o_prime_cm == pytest.approx(outputs["400!C3"], abs=1e-4)


@pytest.mark.oracle
def test_free_golden_case_350():
    outputs = PUNTO_FIXTURE[5]["outputs"]
    inputs = NewmarkInput(modalita="PUNTO", q=1.32 * 98.0665, d=2.20, side_p=3.5, side_q=3.5, e1=1.75, e2=1.75, strati=PUNTO_350_STRATI, legacy_compat=True)
    report = run_newmark(inputs)
    assert report.ok, report.errors
    assert report.data.punto.w_o_cm == pytest.approx(outputs["350!C2"], rel=1e-6)
    assert report.data.punto.w_o_prime_cm == pytest.approx(outputs["350!C3"], abs=1e-4)
