"""Oracle tests for `geo-cedimento-elastico-timoshenko-goodier`, `legacy_compat=True`
(`docs/BUILD_CONTRACT.md` "Tests" §2). Fixture generated by
`tests/fixtures/gen_geo_cedimento_elastico_timoshenko_goodier.py` (sheet
`Elastico_Timoshenko_Goodier_3`)."""
import json
from pathlib import Path

import pytest

from strutture.geotechnics.cedimenti_elastico.models_tg import TimoshenkoGoodierInput
from strutture.geotechnics.cedimenti_elastico.tool_timoshenko_goodier import run_timoshenko_goodier
from strutture.shared.units import kgcm2_to_mpa

FIXTURE = json.loads((Path(__file__).parents[2] / "fixtures" / "geo_cedimento_elastico_timoshenko_goodier_oracle.json").read_text(encoding="utf-8"))

# Ground-surface stratigraphy of `Elastico_Timoshenko_Goodier_3`'s C11:G15. Rows 3-4 are dead
# zero-thickness placeholder rows in the sheet's fixed 5-row table; `SoilLayer` forbids
# zero-thickness rows, so two 1-nanometre padding rows stand in (see the golden-case test module
# for the full rationale). Only "G11" (case 4) is ever overridden.
def _strati(g11_kgcm2: float = 180.0) -> list[dict]:
    return [
        {"z_top_m": 0.0, "z_bot_m": 2.10, "modulo_MPa": kgcm2_to_mpa(g11_kgcm2)},
        {"z_top_m": 2.10, "z_bot_m": 5.00, "modulo_MPa": kgcm2_to_mpa(140.0)},
        {"z_top_m": 5.00, "z_bot_m": 5.00 + 1e-9, "modulo_MPa": kgcm2_to_mpa(140.0)},
        {"z_top_m": 5.00 + 1e-9, "z_bot_m": 5.00 + 2e-9, "modulo_MPa": kgcm2_to_mpa(280.0)},
        {"z_top_m": 5.00 + 2e-9, "z_bot_m": 120.0, "modulo_MPa": kgcm2_to_mpa(280.0)},
    ]


@pytest.mark.oracle
@pytest.mark.parametrize("case", FIXTURE, ids=range(len(FIXTURE)))
def test_oracle_case(case: dict):
    overrides, outputs = case["inputs"], case["outputs"]
    strati = _strati(overrides.get("G11", 180.0))
    inputs = TimoshenkoGoodierInput(
        b=overrides.get("C4", 100) / 100, l=overrides.get("C5", 100) / 100, d=overrides.get("F4", 50) / 100,
        mu=overrides.get("F5", 0.35), q=overrides.get("C6", 0.92) * 98.0665,
        h_significativo=(overrides["C7"] / 100 if "C7" in overrides else None),
        strati=strati, if_centro=overrides.get("U33", 0.65), if_bordo=overrides.get("U36", 0.78),
        legacy_compat=True,
    )
    report = run_timoshenko_goodier(inputs)
    assert report.ok, report.errors
    data = report.data
    assert data.modulo.es_MPa == pytest.approx(kgcm2_to_mpa(outputs["H11"]), rel=1e-6)
    assert data.fattori.is_centro == pytest.approx(outputs["N15"], rel=1e-6)
    assert data.fattori.is_bordo == pytest.approx(outputs["P15"], rel=1e-6)
    assert data.cedimento.delta_h_centro_mm == pytest.approx(outputs["N17"], rel=1e-4)
    assert data.cedimento.delta_h_bordo_mm == pytest.approx(outputs["P17"], rel=1e-4)
