"""Repository interfaces. Business code and routes depend on these Protocols, never on sqlite3."""
from typing import Protocol

from .models import Elemento, Progetto, RevisioneElemento, Signoff, Stato


class SignoffRepository(Protocol):
    def get(self, divergence_id: str) -> Signoff:
        """Current decision; a never-decided id returns Signoff(stato='da_confermare')."""
        ...

    def list_all(self) -> dict[str, Signoff]:
        """Current decision of every id that was ever decided."""
        ...

    def set(self, divergence_id: str, stato: Stato, sigla: str, nota: str = "") -> Signoff:
        """Record a decision (appends to the history) and return the stored record."""
        ...

    def history(self, divergence_id: str) -> tuple[Signoff, ...]:
        """Every decision ever recorded for the id, oldest first."""
        ...


class ConflictError(Exception):
    """Optimistic-locking failure: the record was changed by someone else since it was read."""


class NotFoundError(KeyError):
    """Unknown or deleted id."""


class ProjectRepository(Protocol):
    """Projects and their saved elements. Every update takes the `revisione` the caller last saw and raises
    ConflictError when it is stale (several engineers edit without accounts). Deletes are soft."""

    def list_progetti(self, *, inclusi_eliminati: bool = False) -> tuple[Progetto, ...]: ...
    def get_progetto(self, progetto_id: str) -> Progetto: ...
    def crea_progetto(self, progetto: Progetto) -> Progetto: ...
    def aggiorna_progetto(self, progetto: Progetto) -> Progetto: ...
    def elimina_progetto(self, progetto_id: str, revisione: int) -> None: ...
    def ripristina_progetto(self, progetto_id: str) -> Progetto: ...

    def list_elementi(self, progetto_id: str) -> tuple[Elemento, ...]: ...
    def get_elemento(self, elemento_id: str) -> Elemento: ...
    def crea_elemento(self, elemento: Elemento, *, sigla: str = "", nota: str = "") -> Elemento: ...
    def aggiorna_elemento(self, elemento: Elemento, *, sigla: str = "", nota: str = "") -> Elemento: ...
    def duplica_elemento(self, elemento_id: str, nuovo_nome: str) -> Elemento: ...
    def elimina_elemento(self, elemento_id: str, revisione: int) -> None: ...
    def revisioni(self, elemento_id: str) -> tuple[RevisioneElemento, ...]: ...
