"""Oracle test for `fond-plinto-su-pali`: 3 LibreOffice-recalculated cases of `2xxxx_Plinti su
pali_PL-FX_S&T Eurocode 2.xlsx` (docs/architecture-batch2.md §6), fixture generated by
`tests/fixtures/gen_plinti_pali_oracle.py`. `legacy_compat=True` throughout, per contract."""
import json
from pathlib import Path

import pytest

from strutture.foundations.plinti_pali.tool import TOOLS
from strutture.shared.tool import execute

FIXTURE = json.loads((Path(__file__).parent.parent.parent / "fixtures/plinti_pali_oracle.json").read_text(encoding="utf-8"))
TOOL = TOOLS[0]

# (h_plinto_m, copriferro_cm, lx_m, ly_m, diametro_long_assunto_mm, av_mm,
#  classe_calcestruzzo, grado_acciaio, bx_pilastro_m, by_pilastro_m, diametro_pila_mm)
CASO_SCALARI = [
    (1.2, 5.0, 2.0, 2.0, 24.0, 470.0, "C32/40", "B450C", 0.7, 0.7, 600.0),
    (1.4, 6.0, 2.5, 2.5, 28.0, 350.0, "C32/40", "B450C", 0.7, 0.7, 600.0),
    # `AR107` (pile diameter) only feeds the punching gate cells in the sheet, not `Lb` (`BG13`),
    # which is a separate hardcoded literal (600mm) there — kept at 600mm here too so `puntone.ws_mm`
    # (which this port derives from `diametro_pila_mm` directly, see `puntoni_tiranti.py`) still
    # matches; `AR58/AR59` (column) do not feed any of the asserted cells either.
    (1.2, 5.0, 2.0, 2.0, 24.0, 470.0, "C28/35", "B500C", 0.8, 0.8, 600.0),
]


@pytest.mark.oracle
@pytest.mark.parametrize("indice", range(3))
def test_oracle_inviluppo_flessione_puntoni_taglio(indice: int, golden_rows) -> None:
    caso = FIXTURE[indice]
    out = caso["outputs"]
    (h_plinto_m, copriferro_cm, lx_m, ly_m, diam_long, av_mm, classe_cls, grado_acciaio,
     bx_m, by_m, diametro_pila_mm) = CASO_SCALARI[indice]

    inputs = {
        "schema_pali": "2x2", "lx_m": lx_m, "ly_m": ly_m,
        "ax_m": 4.0, "by_m": 4.0, "h_plinto_m": h_plinto_m, "copriferro_cm": copriferro_cm,
        "bx_pilastro_m": bx_m, "by_pilastro_m": by_m,
        "diametro_pila_mm": diametro_pila_mm, "diametro_long_assunto_mm": diam_long, "av_mm": av_mm,
        "resistenza_pila_compressione_kN": 2000.0,
        "carico_aggiuntivo_kN": 550.7008, "gamma_g1": 1.3,
        "classe_calcestruzzo": classe_cls, "grado_acciaio": grado_acciaio, "gamma_s": 1.15, "gamma_c": 1.5,
        "diametro_inf_x_mm": 24.0, "passo_inf_x_mm": 100.0, "diametro_inf_y_mm": 24.0, "passo_inf_y_mm": 100.0,
        "diametro_sup_x_mm": 24.0, "passo_sup_x_mm": 200.0, "diametro_sup_y_mm": 24.0, "passo_sup_y_mm": 200.0,
        "diametro_tirante_xy_mm": 32.0, "n_tirante_xy": 2,
        "diametro_tirante_x_mm": 24.0, "n_tirante_x": 8, "diametro_tirante_y_mm": 24.0, "n_tirante_y": 8,
        "reazioni": golden_rows, "legacy_compat": True,
    }
    report = execute(TOOL, inputs)
    assert report.ok, report.errors
    data = report.data

    per_grandezza = {r.grandezza: r for r in data.inviluppo}
    assert per_grandezza["n_pila_min"].valore == pytest.approx(out["AF12"], rel=1e-4)
    assert per_grandezza["n_pila_max"].valore == pytest.approx(out["AG12"], rel=1e-4)
    assert per_grandezza["n_totale_max"].valore == pytest.approx(out["AV7"], rel=1e-5)
    assert per_grandezza["n_totale_min"].valore == pytest.approx(out["AV36"], rel=1e-5)
    assert per_grandezza["mx_max"].valore == pytest.approx(out["AZ13"], rel=1e-4)
    assert per_grandezza["mx_min"].valore == pytest.approx(out["AZ14"], rel=1e-4)
    assert per_grandezza["my_max"].valore == pytest.approx(out["AV13"], rel=1e-4)
    assert per_grandezza["my_min"].valore == pytest.approx(out["AV14"], rel=1e-4)

    assert data.flessione.inf_x.as_req_flexural_mm2 == pytest.approx(out["AV20"], rel=1e-3)
    assert data.flessione.inf_y.as_req_flexural_mm2 == pytest.approx(out["AZ20"], rel=1e-3)
    assert data.flessione.inf_x.as_prov_mm2 == pytest.approx(out["AV28"], rel=1e-5)
    assert data.flessione.inf_y.as_prov_mm2 == pytest.approx(out["AZ28"], rel=1e-5)

    puntone = data.puntoni_tiranti.puntone
    assert puntone.theta_deg == pytest.approx(out["BG8"], rel=1e-4)
    assert puntone.fus_kN == pytest.approx(out["BG9"], rel=1e-4)
    assert puntone.sigma_rd_max_MPa == pytest.approx(out["BG12"], rel=1e-4)
    assert puntone.acs_mm2 == pytest.approx(out["BG19"], rel=1e-4)
    assert puntone.fns_kN == pytest.approx(out["BG21"], rel=1e-4)
    assert puntone.utilizzo == pytest.approx(out["BI22"], rel=1e-4)
    assert data.puntoni_tiranti.tirante_xy.fut_kN == pytest.approx(out["BL10"], rel=1e-4)
    assert data.puntoni_tiranti.tirante_x.fut_kN == pytest.approx(out["BL13"], rel=1e-4)

    taglio = data.taglio
    assert taglio.d_mm == pytest.approx(out["AR86"], rel=1e-6)
    assert taglio.ved_kN == pytest.approx(out["AR96"], rel=1e-4)
    assert taglio.ved_ridotto_kN == pytest.approx(out["AR98"], rel=1e-4)
    assert taglio.k == pytest.approx(out["AR99"], rel=1e-4)
    assert taglio.rho == pytest.approx(out["AR100"], rel=1e-4)
    assert taglio.vrd_c_kN == pytest.approx(out["AR103"], rel=1e-4)
    assert taglio.utilizzo == pytest.approx(out["AR104"], rel=1e-4)

    punzonamento = data.punzonamento
    assert punzonamento.u_mm == pytest.approx(out["AR110"], rel=1e-6)
    assert punzonamento.vrd_max_kN == pytest.approx(out["AR111"], rel=1e-4)
    assert punzonamento.utilizzo == pytest.approx(out["AR112"], rel=1e-4)
