"""Oracle test for `fond-plinto-isolato`: 4 LibreOffice-recalculated cases of `2xxxx_Plinti
isolati.xlsx` (docs/architecture-batch2.md §6), fixture generated by
`tests/fixtures/gen_plinti_isolati_oracle.py`. `legacy_compat=True` throughout, per contract."""
import json
from pathlib import Path

import pytest

from strutture.foundations.plinti_isolati.flessione import flessione
from strutture.foundations.plinti_isolati.inviluppo import inviluppo
from strutture.foundations.plinti_isolati.legacy_units import kpa_to_kgcm2
from strutture.foundations.plinti_isolati.materiali import materiali
from strutture.foundations.plinti_isolati.riga_verifica import riga_verifica

FIXTURE = json.loads((Path(__file__).parent.parent.parent / "fixtures/plinti_isolati_oracle.json").read_text(encoding="utf-8"))

# (ax_m, by_m, h_plinto_m, h_interro_m, a_ped_m, b_ped_m, h_ped_sup_m, h_ped_inf_m, offset_leva_m,
#  gamma_terreno, phi_terreno, classe_calcestruzzo, grado_acciaio, copriferro_cm, passo_cm, diam_man_x, diam_man_y)
CASO_SCALARI = [
    (4.0, 4.0, 0.8, 4.5, 0.0, 0.0, 0.0, 0.0, 0.05, 20.0, 30.0, "C35/45", "B500C", 8.0, 12.2, 20.0, 20.0),
    (6.0, 5.0, 0.8, 4.5, 1.0, 1.0, 0.5, 0.3, 0.05, 20.0, 30.0, "C35/45", "B500C", 8.0, 12.2, 20.0, 20.0),
    (4.0, 4.0, 0.8, 4.5, 0.0, 0.0, 0.0, 0.0, 0.15, 18.0, 22.0, "C35/45", "B500C", 8.0, 12.2, 20.0, 20.0),
    (4.0, 4.0, 0.8, 4.5, 0.0, 0.0, 0.0, 0.0, 0.05, 20.0, 30.0, "C32/40", "B450C", 5.0, 15.0, 16.0, 16.0),
]


def _ratio(oracle_value) -> float:
    return 100.0 if oracle_value == ">100" else float(oracle_value)


def _callout(text: str) -> str:
    """Normalise the sheet's own Greek phi (used for its TOP/BOTT callouts) to `shared.rebar_catalog`'s
    'ø' (LATIN SMALL LETTER O WITH STROKE), a cosmetic difference only."""
    return text.replace("φ", "ø")


@pytest.mark.oracle
@pytest.mark.parametrize("indice", range(4))
def test_oracle_riga_e_inviluppo(indice: int, golden_rows) -> None:
    caso = FIXTURE[indice]
    out = caso["outputs"]
    (ax_m, by_m, h_plinto_m, h_interro_m, a_ped_m, b_ped_m, h_ped_sup_m, h_ped_inf_m, offset_leva_m,
     gamma_terreno, phi_terreno, classe_cls, grado_acciaio, copriferro_cm, passo_cm, diam_x, diam_y) = CASO_SCALARI[indice]

    righe = tuple(
        riga_verifica(row, ax_m, by_m, h_plinto_m, h_interro_m, a_ped_m, b_ped_m, h_ped_sup_m, h_ped_inf_m,
                      offset_leva_m, 0.0, 0.0, gamma_terreno, phi_terreno,
                      metodo_pressioni="sovrapposizione", legacy_compat=True)
        for row in golden_rows
    )
    riga0 = righe[0]  # CHECKS!row6, first combo (ULS1).
    assert riga0.n_kN == pytest.approx(out["CHECKS!G6"], rel=1e-5)
    assert riga0.myy_kNm == pytest.approx(out["CHECKS!I6"], rel=1e-5)
    assert riga0.mxx_kNm == pytest.approx(out["CHECKS!L6"], rel=1e-5)
    assert riga0.ex_m == pytest.approx(out["CHECKS!M6"], rel=1e-4)
    assert riga0.ey_m == pytest.approx(out["CHECKS!T6"], rel=1e-4)
    assert riga0.compressed_ratio == pytest.approx(out["CHECKS!AP6"], rel=1e-6)
    assert kpa_to_kgcm2(riga0.sigma_max_kpa, legacy_compat=True) == pytest.approx(out["CHECKS!AA6"], rel=1e-4)
    assert riga0.mu_ribaltamento_x == pytest.approx(_ratio(out["CHECKS!AE6"]), rel=1e-4)
    assert riga0.mu_ribaltamento_y == pytest.approx(_ratio(out["CHECKS!AH6"]), rel=1e-4)
    assert riga0.mu_scorrimento == pytest.approx(_ratio(out["CHECKS!AM6"]), rel=1e-4)

    inviluppo_righe = inviluppo(righe)
    per_famiglia = {(r.grandezza, r.famiglia): r for r in inviluppo_righe}
    assert per_famiglia[("pressione_max_kpa", "SLU_STR")].valore / 100.0 == pytest.approx(out["L16"], rel=1e-4)
    assert per_famiglia[("pressione_max_kpa", "SLU_STR")].combo == out["N16"]
    assert per_famiglia[("scorrimento_min", "SLU_STR")].valore == pytest.approx(_ratio(out["P16"]), rel=1e-3)
    assert per_famiglia[("scorrimento_min", "SLU_STR")].combo == out["R16"]

    materiali_result = materiali(classe_cls, grado_acciaio, 1.15, legacy_compat=True)
    assert materiali_result.acciaio.fyd_MPa == pytest.approx(out["T5"], rel=1e-5)
    assert materiali_result.calcestruzzo.fck_MPa == pytest.approx(out["T7"], rel=1e-5)
    assert materiali_result.calcestruzzo.fctm_MPa == pytest.approx(out["T8"], rel=1e-5)

    flessione_result = flessione(
        inviluppo_righe, ax_m, by_m, h_plinto_m, a_ped_m, b_ped_m, 0.0, 0.0, copriferro_cm, passo_cm, diam_x, diam_y,
        materiali_result.acciaio.fyd_MPa, materiali_result.acciaio.fyk_MPa, materiali_result.calcestruzzo.fctm_MPa,
        legacy_compat=True,
    )
    assert flessione_result.mx_slu_kNm == pytest.approx(out["T13"], rel=1e-4)
    assert flessione_result.my_slu_kNm == pytest.approx(out["T14"], rel=1e-4)
    assert flessione_result.as_x_cm2 == pytest.approx(out["T15"], rel=1e-3)  # Asx = f(Mx,SLU=T13)
    assert flessione_result.as_y_cm2 == pytest.approx(out["T16"], rel=1e-3)  # Asy = f(My,SLU=T14)
    assert flessione_result.as_x_min_cm2 == pytest.approx(out["T17"], rel=1e-6)
    assert flessione_result.as_y_min_cm2 == pytest.approx(out["T18"], rel=1e-6)
    assert flessione_result.n_x == out["T19"]
    assert flessione_result.n_y == out["T20"]
    assert flessione_result.phi_min_mm == pytest.approx(out["T25"], rel=1e-6)
    assert flessione_result.callout_sup_x == _callout(out["T30"])
    assert flessione_result.callout_sup_y == _callout(out["U30"])
    assert flessione_result.callout_inf_x == _callout(out["T31"])
    assert flessione_result.callout_inf_y == _callout(out["U31"])
